"""empty message

Revision ID: c27fb89e4a7e
Revises: 9fccf836889d
Create Date: 2024-04-01 20:04:04.009138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c27fb89e4a7e'
down_revision = '9fccf836889d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abstract', sa.String(length=225), nullable=False))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('content_html', sa.Text(), nullable=False))
        batch_op.drop_column('body')
        batch_op.drop_column('summary')
        batch_op.drop_column('body_html')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('summary', mysql.VARCHAR(length=225), nullable=False))
        batch_op.add_column(sa.Column('body', mysql.TEXT(), nullable=False))
        batch_op.drop_column('content_html')
        batch_op.drop_column('content')
        batch_op.drop_column('abstract')

    # ### end Alembic commands ###
